### ISSUE TITLE
1.2.0 with renderMode: single renders all labels with the same content

### ISSUE THREAD

**Issue by Dervisevic** [devcode-git/hosted-fields-sdk#12]
I'm testing out 1.2.0, love the improvements and introduction of the single render mode. However, when rendering single, all labels render with the same content. My implementation uses the fieldconfig below, and now all labels get the value in the last element of the array.

<img width="499" alt="Screenshot 2020-11-10 at 12 29 19" src="https://user-images.githubusercontent.com/541475/98787093-54b96180-23ff-11eb-9a3d-f1a8d759a6e4.png">

FieldConfig:
```json
[
  {
    "type": "CREDITCARD_NUMBER",
    "id": "creditcard",
    "name": "creditcard",
    "label": "Kortnummer",
    "errorKey": "Ogiltigt kortnummer",
    "noAttributeValueFormatting": true,
    "autocomplete": "cc-number",
    "visible": true
  },
  {
    "type": "EXPIRY_MM_YYYY",
    "id": "dateExpire",
    "name": "date-expire",
    "label": "MM/ÅÅÅÅ",
    "errorKey": "Ogiltigt giltighetsdatum",
    "noAttributeValueFormatting": true,
    "autocomplete": "cc-exp",
    "visible": true
  },
  {
    "type": "CVV",
    "id": "cvv",
    "name": "cvv",
    "label": "Säkerhetskod",
    "errorKey": "Ogiltig CVC",
    "noAttributeValueFormatting": true,
    "autocomplete": "cc-csc",
    "visible": true
  }
]
```

**Comment by ssolders** [comment]
Glad to hear it. Bugfix has been fixed and deployed, it should work right away without any updates on your end (other than maybe clearing your cache)

Please reach out if you experience any other issues.
